version: "3.9"

volumes:
  wordpress_data:

networks:
  trial-mysql_backend:
    external: true

services:
  wordpress:
    container_name: wordpress
    image: wordpress:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html
      # - type: bind
      #   source: ./wordpress/
      #   target: /var/www/html
    networks:
      - trial-mysql_backend
