version: "3.9"

volumes:
  wordpress_data:

networks:
  trial-mysql_backend:
    external: true

services:
  wordpress:
    container_name: wordpress
    image: wordpress:6.4-php8.3
    restart: always
    env_file: .env
    ports:
      - ${PORT-80}:80
    volumes:
      - type: volume
        source: wordpress_data
        target: /var/www/html
      # - type: bind
      #   source: ./wordpress
      #   target: /var/www/html
    networks:
      - trial-mysql_backend
